[package]
name = "glass_engine"
version = "1.0.0"
edition = "2021"

[[bin]]
name="glass_eng"
path = "drops/gl.rs"

[lib]
path = "drops/gl.rs"
opt-level = "z"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"